// <auto-generated />
namespace Messenger.Server
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddedToChatMessagesList : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedToChatMessagesList));
        
        string IMigrationMetadata.Id
        {
            get { return "202101241236291_AddedToChatMessagesList"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
